// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: merchandising/merchandising.proto

package merchandising

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"title",validate:"required"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title" validate:"required"`
	// @inject_tag: json:"name",validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" validate:"required"`
	// @inject_tag: json:"icon",validate:"required,url"
	Icon string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon" validate:"required,url"`
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestCreate) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type RequestDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id",validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required"`
}

func (x *RequestDetails) Reset() {
	*x = RequestDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDetails) ProtoMessage() {}

func (x *RequestDetails) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDetails.ProtoReflect.Descriptor instead.
func (*RequestDetails) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResponseDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon  string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *ResponseDetails) Reset() {
	*x = ResponseDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDetails) ProtoMessage() {}

func (x *ResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDetails.ProtoReflect.Descriptor instead.
func (*ResponseDetails) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResponseDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseDetails) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type RequestExist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"amenities",validate:"required"
	Amenities []string `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities" validate:"required"`
}

func (x *RequestExist) Reset() {
	*x = RequestExist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestExist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExist) ProtoMessage() {}

func (x *RequestExist) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExist.ProtoReflect.Descriptor instead.
func (*RequestExist) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{3}
}

func (x *RequestExist) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type ResponseExist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResponseExist) Reset() {
	*x = ResponseExist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseExist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseExist) ProtoMessage() {}

func (x *ResponseExist) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseExist.ProtoReflect.Descriptor instead.
func (*ResponseExist) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseExist) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type RequestFindByIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"amenities",validate:"required"
	Amenities []string `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities" validate:"required"`
}

func (x *RequestFindByIds) Reset() {
	*x = RequestFindByIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFindByIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFindByIds) ProtoMessage() {}

func (x *RequestFindByIds) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFindByIds.ProtoReflect.Descriptor instead.
func (*RequestFindByIds) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{5}
}

func (x *RequestFindByIds) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type ResponseFindByIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amenities []*ResponseDetails `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities,omitempty"`
}

func (x *ResponseFindByIds) Reset() {
	*x = ResponseFindByIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merchandising_merchandising_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseFindByIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFindByIds) ProtoMessage() {}

func (x *ResponseFindByIds) ProtoReflect() protoreflect.Message {
	mi := &file_merchandising_merchandising_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFindByIds.ProtoReflect.Descriptor instead.
func (*ResponseFindByIds) Descriptor() ([]byte, []int) {
	return file_merchandising_merchandising_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseFindByIds) GetAmenities() []*ResponseDetails {
	if x != nil {
		return x.Amenities
	}
	return nil
}

var File_merchandising_merchandising_proto protoreflect.FileDescriptor

var file_merchandising_merchandising_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79,
	0x22, 0x4d, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22,
	0x20, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x5f, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x10, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x11, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x73,
	0x12, 0x36, 0x0a, 0x09, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x09, 0x61,
	0x6d, 0x65, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x32, 0x93, 0x02, 0x0a, 0x0e, 0x41, 0x6d, 0x65,
	0x6e, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x18, 0x2e,
	0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x17, 0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x18, 0x2e,
	0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74,
	0x79, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x73,
	0x1a, 0x1a, 0x2e, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x73, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_merchandising_merchandising_proto_rawDescOnce sync.Once
	file_merchandising_merchandising_proto_rawDescData = file_merchandising_merchandising_proto_rawDesc
)

func file_merchandising_merchandising_proto_rawDescGZIP() []byte {
	file_merchandising_merchandising_proto_rawDescOnce.Do(func() {
		file_merchandising_merchandising_proto_rawDescData = protoimpl.X.CompressGZIP(file_merchandising_merchandising_proto_rawDescData)
	})
	return file_merchandising_merchandising_proto_rawDescData
}

var file_merchandising_merchandising_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_merchandising_merchandising_proto_goTypes = []interface{}{
	(*RequestCreate)(nil),     // 0: merchandising.RequestCreate
	(*RequestDetails)(nil),    // 1: merchandising.RequestDetails
	(*ResponseDetails)(nil),   // 2: merchandising.ResponseDetails
	(*RequestExist)(nil),      // 3: merchandising.RequestExist
	(*ResponseExist)(nil),     // 4: merchandising.ResponseExist
	(*RequestFindByIds)(nil),  // 5: merchandising.RequestFindByIds
	(*ResponseFindByIds)(nil), // 6: merchandising.ResponseFindByIds
}
var file_merchandising_merchandising_proto_depIdxs = []int32{
	2, // 0: merchandising.ResponseFindByIds.amenities:type_name -> merchandising.ResponseDetails
	0, // 1: merchandising.merchandisingService.Create:input_type -> merchandising.RequestCreate
	1, // 2: merchandising.merchandisingService.Details:input_type -> merchandising.RequestDetails
	3, // 3: merchandising.merchandisingService.CheckExist:input_type -> merchandising.RequestExist
	5, // 4: merchandising.merchandisingService.FindByIds:input_type -> merchandising.RequestFindByIds
	2, // 5: merchandising.merchandisingService.Create:output_type -> merchandising.ResponseDetails
	2, // 6: merchandising.merchandisingService.Details:output_type -> merchandising.ResponseDetails
	4, // 7: merchandising.merchandisingService.CheckExist:output_type -> merchandising.ResponseExist
	6, // 8: merchandising.merchandisingService.FindByIds:output_type -> merchandising.ResponseFindByIds
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchandising_merchandising_proto_init() }
func file_merchandising_merchandising_proto_init() {
	if File_merchandising_merchandising_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_merchandising_merchandising_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merchandising_merchandising_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merchandising_merchandising_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merchandising_merchandising_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestExist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merchandising_merchandising_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseExist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merchandising_merchandising_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFindByIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merchandising_merchandising_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseFindByIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_merchandising_merchandising_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchandising_merchandising_proto_goTypes,
		DependencyIndexes: file_merchandising_merchandising_proto_depIdxs,
		MessageInfos:      file_merchandising_merchandising_proto_msgTypes,
	}.Build()
	File_merchandising_merchandising_proto = out.File
	file_merchandising_merchandising_proto_rawDesc = nil
	file_merchandising_merchandising_proto_goTypes = nil
	file_merchandising_merchandising_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// merchandisingServiceClient is the client API for merchandisingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type merchandisingServiceClient interface {
	Create(ctx context.Context, in *RequestCreate, opts ...grpc.CallOption) (*ResponseDetails, error)
	Details(ctx context.Context, in *RequestDetails, opts ...grpc.CallOption) (*ResponseDetails, error)
	CheckExist(ctx context.Context, in *RequestExist, opts ...grpc.CallOption) (*ResponseExist, error)
	FindByIds(ctx context.Context, in *RequestFindByIds, opts ...grpc.CallOption) (*ResponseFindByIds, error)
}

type merchandisingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewmerchandisingServiceClient(cc grpc.ClientConnInterface) merchandisingServiceClient {
	return &merchandisingServiceClient{cc}
}

func (c *merchandisingServiceClient) Create(ctx context.Context, in *RequestCreate, opts ...grpc.CallOption) (*ResponseDetails, error) {
	out := new(ResponseDetails)
	err := c.cc.Invoke(ctx, "/merchandising.merchandisingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchandisingServiceClient) Details(ctx context.Context, in *RequestDetails, opts ...grpc.CallOption) (*ResponseDetails, error) {
	out := new(ResponseDetails)
	err := c.cc.Invoke(ctx, "/merchandising.merchandisingService/Details", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchandisingServiceClient) CheckExist(ctx context.Context, in *RequestExist, opts ...grpc.CallOption) (*ResponseExist, error) {
	out := new(ResponseExist)
	err := c.cc.Invoke(ctx, "/merchandising.merchandisingService/CheckExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchandisingServiceClient) FindByIds(ctx context.Context, in *RequestFindByIds, opts ...grpc.CallOption) (*ResponseFindByIds, error) {
	out := new(ResponseFindByIds)
	err := c.cc.Invoke(ctx, "/merchandising.merchandisingService/FindByIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// merchandisingServiceServer is the server API for merchandisingService service.
type merchandisingServiceServer interface {
	Create(context.Context, *RequestCreate) (*ResponseDetails, error)
	Details(context.Context, *RequestDetails) (*ResponseDetails, error)
	CheckExist(context.Context, *RequestExist) (*ResponseExist, error)
	FindByIds(context.Context, *RequestFindByIds) (*ResponseFindByIds, error)
}

// UnimplementedmerchandisingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedmerchandisingServiceServer struct {
}

func (*UnimplementedmerchandisingServiceServer) Create(context.Context, *RequestCreate) (*ResponseDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedmerchandisingServiceServer) Details(context.Context, *RequestDetails) (*ResponseDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Details not implemented")
}
func (*UnimplementedmerchandisingServiceServer) CheckExist(context.Context, *RequestExist) (*ResponseExist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExist not implemented")
}
func (*UnimplementedmerchandisingServiceServer) FindByIds(context.Context, *RequestFindByIds) (*ResponseFindByIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByIds not implemented")
}

func RegistermerchandisingServiceServer(s *grpc.Server, srv merchandisingServiceServer) {
	s.RegisterService(&_merchandisingService_serviceDesc, srv)
}

func _merchandisingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(merchandisingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchandising.merchandisingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(merchandisingServiceServer).Create(ctx, req.(*RequestCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _merchandisingService_Details_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(merchandisingServiceServer).Details(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchandising.merchandisingService/Details",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(merchandisingServiceServer).Details(ctx, req.(*RequestDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _merchandisingService_CheckExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestExist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(merchandisingServiceServer).CheckExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchandising.merchandisingService/CheckExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(merchandisingServiceServer).CheckExist(ctx, req.(*RequestExist))
	}
	return interceptor(ctx, in, info, handler)
}

func _merchandisingService_FindByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFindByIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(merchandisingServiceServer).FindByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchandising.merchandisingService/FindByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(merchandisingServiceServer).FindByIds(ctx, req.(*RequestFindByIds))
	}
	return interceptor(ctx, in, info, handler)
}

var _merchandisingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "merchandising.merchandisingService",
	HandlerType: (*merchandisingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _merchandisingService_Create_Handler,
		},
		{
			MethodName: "Details",
			Handler:    _merchandisingService_Details_Handler,
		},
		{
			MethodName: "CheckExist",
			Handler:    _merchandisingService_CheckExist_Handler,
		},
		{
			MethodName: "FindByIds",
			Handler:    _merchandisingService_FindByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchandising/merchandising.proto",
}
